spring:
  application:
    name: docshelper
  profiles:
    include:
      - key
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.mysql.server}
    username: ENC(aK96+/1gVVUtIV7lzTgavA==)
    password: ENC(X1TFqz2bGD5IMts6sOxRsoDeQP4n2scl)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api

#springdoc swagger
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui/docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    display-request-duration: true

oauth2:
  google:
    client-id: ENC(BLCB0WfVVM62jPLgQcEbnGczWTO26GrhNHQLSKEjg77DY/tS5Le/pQofyDLbBCiz44RHqvkTioWpQEBpatlawf429YJKdwcwHzJNCWYBaHEA+ZWKEoPkSQ==)
    client-secret: ENC(T7lZR5pOkUNQd+c8sFtK2ahvatXX8STB49tej7ex+XzJo2RveOdFLWnh43CfVo+K)
    redirect-uri:
      local: ENC(GZfCHdh284uESChWedFUfwpEgppqdlfyE1RkSJPGrcrb675Q81q1L3OOMyDPzmyg3dsEgMRlQpE=)
      dev: ENC(IhPpvDrd2HDI2VVYuYvXNFERomrjS/mQdyQW0bE/8nkeWDlESxClDQ7/1ZujFr+V3ImMf5dhDSY=)
    token-uri: ENC(+DvxpEFqL29rxdHsIOQmAsoadq3jnzLzcvvgAUbQ670RBFLgdtfyt7sKZjKvsjWd)
    resource-uri: ENC(mUB8ZfrAPUubt0Z/XvS9yFQoMcWJPQa+ASL2+Jhn35u2qDRHoJqKsds7VQ9e+sZ07vszt4Ux4vI=)

jwt:
  secret: ENC(dTQuX11BrDFtcUjBGutl+Ro3w2aQ8XYINrRlo6EN4Delt0a3CMY+ruOpM2B2pDoUmFvT4JiI8p+5lZFIEOZo97hcYJZVzv9Pm1Tzo/97dKQ+Wrc0fOD+5jKptZ6ClmALG00xBHduspvn+wya+1bV6QvZya/gT+14YHw49+TG1xBXFHAwERjQwl6flHHTpwAN)
  token:
    access-expiration-time: 259200000 # 12시간
    refresh-expiration-time: 259200000 # 3일

#aws s3 bucket
cloud:
  aws:
    s3:
      bucket: ENC(ZSHbUr/zXFOQcSI3y54nHiXlAsxw563p)
    credentials:
      access-key: ENC(1e9KxmFrWk0TQJ7QwlDEK7aPFTR2+wi07811K9kYs34=)
      secret-key: ENC(eLr+oY8wKNE+8ka2LqcstS3jWYPHwEJr80m8DBJG/V4BKVbfGzZuQAlrKlwhzFYvz7Y6ZwFHu0k=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

  # OCR TEMPLATE API URL
  naver:
    template-ocr-url: ENC(FTVYlo/LiNoWqajfGj5Nrtl3+6w/YzKzxMMWR/uWp1wUotJq+88KvefUyaF7CbMZOnQUwM8C5Ei1uUFgAjGOVUjcBfVQaKBFgbfhMVY6GPlLcdMI/P/8Ou/JEiUhqu4rNG9XN+9vG9DEworGzemiq40JdnIkrteNTJtPuioGVl/EzMa37AN8XQ==)
    secret: ENC(HDwud1PVTG9WybSFNsyFjy1o7WTIKpYKZMgqHT2IbMDmQqfmvnxcCHx7K97rh6ezRk2VmYTAJMw=)